C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 15 Jan 2021 14:26
C
C  Differentiation of cross in reverse (adjoint) mode (with options i4 dr8 r8):
C   gradient     of useful results: u v w
C   with respect to varying inputs: u v w
C SRDSET
C
C
C
      SUBROUTINE CROSS_B(u, u_diff, v, v_diff, w, w_diff)
      REAL u(3), v(3), w(3)
      REAL u_diff(3), v_diff(3), w_diff(3)
      u_diff(1) = u_diff(1) + v(2)*w_diff(3) - v(3)*w_diff(2)
      v_diff(2) = v_diff(2) + u(1)*w_diff(3) - u(3)*w_diff(1)
      u_diff(2) = u_diff(2) + v(3)*w_diff(1) - v(1)*w_diff(3)
      v_diff(1) = v_diff(1) + u(3)*w_diff(2) - u(2)*w_diff(3)
      w_diff(3) = 0.D0
      u_diff(3) = u_diff(3) + v(1)*w_diff(2) - v(2)*w_diff(1)
      v_diff(3) = v_diff(3) + u(2)*w_diff(1) - u(1)*w_diff(2)
      w_diff(2) = 0.D0
      w_diff(1) = 0.D0
      END

C  Differentiation of dot in reverse (adjoint) mode (with options i4 dr8 r8):
C   gradient     of useful results: u v dot
C   with respect to varying inputs: u v
C
C
      SUBROUTINE DOT_B(u, u_diff, v, v_diff, dot_diff)
      REAL u(3), v(3)
      REAL u_diff(3), v_diff(3)
      REAL dot
      REAL dot_diff
      u_diff(1) = u_diff(1) + v(1)*dot_diff
      v_diff(1) = v_diff(1) + u(1)*dot_diff
      u_diff(2) = u_diff(2) + v(2)*dot_diff
      v_diff(2) = v_diff(2) + u(2)*dot_diff
      u_diff(3) = u_diff(3) + v(3)*dot_diff
      v_diff(3) = v_diff(3) + u(3)*dot_diff
      END

