C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 15 Jan 2021 14:26
C
C  Differentiation of set_params in reverse (adjoint) mode (with options i4 dr8 r8):
C   gradient     of useful results: parval mach
C   with respect to varying inputs: parval
C RUNLST
C
C
      SUBROUTINE SET_PARAMS_B(ir)
      INCLUDE 'AVL.INC'
      INCLUDE 'AVL_ad_seeds.inc'
      INTEGER ir
      REAL phi
      REAL the
      REAL vee
      REAL rho
      REAL gee
      REAL rmass
      REAL rixx
      REAL riyy
      REAL rizz
      REAL xcg
      REAL ycg
      REAL zcg
      REAL cd0
      REAL dcl_a
      REAL dcl_u
      REAL dcm_a
      REAL dcm_u
      parval_diff(ipmach, ir) = parval_diff(ipmach, ir) + mach_diff
      END

