C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 15 Jan 2021 14:26
C
C  Differentiation of get_res in reverse (adjoint) mode (with options i4 dr8 r8):
C   gradient     of useful results: res
C   with respect to varying inputs: alfa res
C   RW status of diff variables: alfa:out res:in-zero
Csubroutine solve_rhs
      SUBROUTINE GET_RES_B()
      INCLUDE 'AVL.INC'
      INCLUDE 'AVL_ad_seeds.inc'
      INTEGER i
      INTEGER ii1
C IF(.NOT.LAIC) THEN
C       call factor_AIC
C ENDIF
C---  
      IF (.NOT.laic) CALL BUILD_AIC()
C---- set VINF() vector from initial ALFA,BETA
      CALL VINFAB()
C
      DO ii1=1,nvmax
        rhs_diff(ii1) = 0.D0
      ENDDO
      DO i=nvor,1,-1
        rhs_diff(i) = rhs_diff(i) - res_diff(i)
      ENDDO
      CALL SET_VEL_RHS_B()
      CALL VINFAB_B()
      END
Cget_res

