C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 15 Jan 2021 14:26
C
C  Differentiation of set_vel_rhs in reverse (adjoint) mode (with options i4 dr8 r8):
C   gradient     of useful results: rhs
C   with respect to varying inputs: vinf
C WSENS
      SUBROUTINE SET_VEL_RHS_B()
C
      INCLUDE 'AVL.INC'
      INCLUDE 'AVL_ad_seeds.inc'
      REAL rrot(3), vunit(3), vunit_w_term(3), wunit(3)
      REAL vunit_diff(3)
      INTEGER i
      REAL DOT
      REAL result1
      REAL result1_diff
      INTEGER branch
      DO i=1,nvor
        IF (lvnc(i)) THEN
          CALL PUSHREAL8(vunit(1))
          vunit(1) = 0.
          CALL PUSHREAL8(vunit(2))
          vunit(2) = 0.
          CALL PUSHREAL8(vunit(3))
          vunit(3) = 0.
          wunit(1) = 0.
          wunit(2) = 0.
          wunit(3) = 0.
          IF (lvalbe(i)) THEN
            CALL PUSHREAL8(vunit(1))
            vunit(1) = vinf(1)
            CALL PUSHREAL8(vunit(2))
            vunit(2) = vinf(2)
            CALL PUSHREAL8(vunit(3))
            vunit(3) = vinf(3)
            wunit(1) = wrot(1)
            wunit(2) = wrot(2)
            wunit(3) = wrot(3)
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHCONTROL1B(1)
          END IF
          rrot(1) = rc(1, i) - xyzref(1)
          rrot(2) = rc(2, i) - xyzref(2)
          rrot(3) = rc(3, i) - xyzref(3)
          CALL CROSS(rrot, wunit, vunit_w_term)
          CALL PUSHREAL8ARRAY(vunit, 3)
          vunit = vunit + vunit_w_term
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
        END IF
      ENDDO
      vinf_diff = 0.D0
      vunit_diff = 0.D0
      DO i=nvor,1,-1
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          rhs_diff(i) = 0.D0
        ELSE
          result1_diff = -rhs_diff(i)
          rhs_diff(i) = 0.D0
          enc_diff = 0.D0
          CALL DOT_B(enc(1, i), enc_diff(1, i), vunit, vunit_diff, 
     +               result1_diff)
          CALL POPREAL8ARRAY(vunit, 3)
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            CALL POPREAL8(vunit(3))
            vinf_diff(3) = vinf_diff(3) + vunit_diff(3)
            vunit_diff(3) = 0.D0
            CALL POPREAL8(vunit(2))
            vinf_diff(2) = vinf_diff(2) + vunit_diff(2)
            vunit_diff(2) = 0.D0
            CALL POPREAL8(vunit(1))
            vinf_diff(1) = vinf_diff(1) + vunit_diff(1)
            vunit_diff(1) = 0.D0
          END IF
          CALL POPREAL8(vunit(3))
          vunit_diff(3) = 0.D0
          CALL POPREAL8(vunit(2))
          vunit_diff(2) = 0.D0
          CALL POPREAL8(vunit(1))
          vunit_diff(1) = 0.D0
        END IF
      ENDDO
      END

