C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 15 Jan 2021 14:26
C
C  Differentiation of cross in forward (tangent) mode (with options i4 dr8 r8):
C   variations   of useful results: w
C   with respect to varying inputs: u v w
C SRDSET
C
C
C
      SUBROUTINE CROSS_D(u, u_diff, v, v_diff, w, w_diff)
      REAL u(3), v(3), w(3)
      REAL u_diff(3), v_diff(3), w_diff(3)
      w_diff(1) = v(3)*u_diff(2) + u(2)*v_diff(3) - v(2)*u_diff(3) - u(3
     +  )*v_diff(2)
      w(1) = u(2)*v(3) - u(3)*v(2)
      w_diff(2) = v(1)*u_diff(3) + u(3)*v_diff(1) - v(3)*u_diff(1) - u(1
     +  )*v_diff(3)
      w(2) = u(3)*v(1) - u(1)*v(3)
      w_diff(3) = v(2)*u_diff(1) + u(1)*v_diff(2) - v(1)*u_diff(2) - u(2
     +  )*v_diff(1)
      w(3) = u(1)*v(2) - u(2)*v(1)
      RETURN
      END

C  Differentiation of dot in forward (tangent) mode (with options i4 dr8 r8):
C   variations   of useful results: dot
C   with respect to varying inputs: u v
C
C
      FUNCTION DOT_D(u, u_diff, v, v_diff, dot)
      REAL u(3), v(3)
      REAL u_diff(3), v_diff(3)
      REAL dot
      REAL dot_d
      dot_d = v(1)*u_diff(1) + u(1)*v_diff(1) + v(2)*u_diff(2) + u(2)*
     +  v_diff(2) + v(3)*u_diff(3) + u(3)*v_diff(3)
      dot = u(1)*v(1) + u(2)*v(2) + u(3)*v(3)
      RETURN
      END

