C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 15 Jan 2021 14:26
C
C  Differentiation of cross in forward (tangent) mode (with options i4 dr8 r8):
C   variations   of useful results: w
C   with respect to varying inputs: u v w
C SRDSET
C
C
C
      SUBROUTINE CROSS_D(u, ud, v, vd, w, wd)
      IMPLICIT NONE
      REAL u(3), v(3), w(3)
      REAL ud(3), vd(3), wd(3)
      wd(1) = v(3)*ud(2) + u(2)*vd(3) - v(2)*ud(3) - u(3)*vd(2)
      w(1) = u(2)*v(3) - u(3)*v(2)
      wd(2) = v(1)*ud(3) + u(3)*vd(1) - v(3)*ud(1) - u(1)*vd(3)
      w(2) = u(3)*v(1) - u(1)*v(3)
      wd(3) = v(2)*ud(1) + u(1)*vd(2) - v(1)*ud(2) - u(2)*vd(1)
      w(3) = u(1)*v(2) - u(2)*v(1)
      RETURN
      END

C  Differentiation of dot in forward (tangent) mode (with options i4 dr8 r8):
C   variations   of useful results: dot
C   with respect to varying inputs: u v
C
C
      FUNCTION DOT_D(u, ud, v, vd, dot)
      IMPLICIT NONE
      REAL u(3), v(3)
      REAL ud(3), vd(3)
      REAL dot
      REAL dot_d
      dot_d = v(1)*ud(1) + u(1)*vd(1) + v(2)*ud(2) + u(2)*vd(2) + v(3)*
     +  ud(3) + u(3)*vd(3)
      dot = u(1)*v(1) + u(2)*v(2) + u(3)*v(3)
      RETURN
      END

