C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 15 Jan 2021 14:26
C
C  Differentiation of set_params in forward (tangent) mode (with options i4 dr8 r8):
C   variations   of useful results: mach
C   with respect to varying inputs: parval
C RUNLST
C
C
      SUBROUTINE SET_PARAMS_D(ir)
      INCLUDE 'AVL.INC'
      INCLUDE 'AVL_ad_seeds.inc'
      INTEGER ir
      REAL phi
      REAL the
      REAL vee
      REAL rho
      REAL gee
      REAL rmass
      REAL rixx
      REAL riyy
      REAL rizz
      REAL xcg
      REAL ycg
      REAL zcg
      REAL cd0
      REAL dcl_a
      REAL dcl_u
      REAL dcm_a
      REAL dcm_u
      phi = parval(ipphi, ir)
      the = parval(ipthe, ir)
      mach_diff = parval_diff(ipmach, ir)
      mach = parval(ipmach, ir)
      vee = parval(ipvee, ir)
      rho = parval(iprho, ir)
      gee = parval(ipgee, ir)
      rmass = parval(ipmass, ir)
      rixx = parval(ipixx, ir)
      riyy = parval(ipiyy, ir)
      rizz = parval(ipizz, ir)
      xcg = parval(ipxcg, ir)
      ycg = parval(ipycg, ir)
      zcg = parval(ipzcg, ir)
      cd0 = parval(ipcd0, ir)
      dcl_a = parval(ipcla, ir)
      dcl_u = parval(ipclu, ir)
      dcm_a = parval(ipcma, ir)
      dcm_u = parval(ipcmu, ir)
      END

