C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 15 Jan 2021 14:26
C
C  Differentiation of get_res in forward (tangent) mode (with options i4 dr8 r8):
C   variations   of useful results: vinf res
C   with respect to varying inputs: ysym zsym alfa beta xyzref
C                mach rv1 rv2 rc chordv enc gam
C   RW status of diff variables: ysym:in zsym:in alfa:in beta:in
C                vinf:out xyzref:in mach:in rv1:in rv2:in rc:in
C                chordv:in enc:in gam:in res:out
Csubroutine solve_rhs
      SUBROUTINE GET_RES_D()
      INCLUDE 'AVL.INC'
      INCLUDE 'AVL_ad_seeds.inc'
      INTEGER i
C---  
      CALL BUILD_AIC_D()
C---- set VINF() vector from initial ALFA,BETA
      CALL VINFAB_D()
      CALL SET_VEL_RHS_D()
C
      CALL MAT_PROD_D(aicn, aicn_diff, gam, gam_diff, nvor, res, 
     +                res_diff)
C---- add the RHS vector to the residual
      DO i=1,nvor
        res_diff(i) = res_diff(i) - rhs_diff(i)
        res(i) = res(i) - rhs(i)
      ENDDO
      END

