C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 15 Jan 2021 14:26
C
C  Differentiation of set_vel_rhs in forward (tangent) mode (with options i4 dr8 r8):
C   variations   of useful results: rhs
C   with respect to varying inputs: vinf
C WSENS
      SUBROUTINE SET_VEL_RHS_D()
C
      INCLUDE 'AVL.INC'
      INCLUDE 'AVL_ad_seeds.inc'
      REAL rrot(3), vunit(3), vunit_w_term(3), wunit(3)
      REAL vunit_diff(3)
      INTEGER i
      REAL DOT
      REAL DOT_D
      REAL result1
      REAL result1_diff
      rhs_diff = 0.D0
      vunit_diff = 0.D0
      DO i=1,nvor
        IF (lvnc(i)) THEN
          vunit_diff(1) = 0.D0
          vunit(1) = 0.
          vunit_diff(2) = 0.D0
          vunit(2) = 0.
          vunit_diff(3) = 0.D0
          vunit(3) = 0.
          wunit(1) = 0.
          wunit(2) = 0.
          wunit(3) = 0.
          IF (lvalbe(i)) THEN
            vunit_diff(1) = vinf_diff(1)
            vunit(1) = vinf(1)
            vunit_diff(2) = vinf_diff(2)
            vunit(2) = vinf(2)
            vunit_diff(3) = vinf_diff(3)
            vunit(3) = vinf(3)
            wunit(1) = wrot(1)
            wunit(2) = wrot(2)
            wunit(3) = wrot(3)
          END IF
          rrot(1) = rc(1, i) - xyzref(1)
          rrot(2) = rc(2, i) - xyzref(2)
          rrot(3) = rc(3, i) - xyzref(3)
          CALL CROSS(rrot, wunit, vunit_w_term)
          vunit = vunit + vunit_w_term
          enc_diff = 0.D0
          result1_diff = DOT_D(enc(1, i), enc_diff(1, i), vunit, 
     +      vunit_diff, result1)
          rhs_diff(i) = -result1_diff
          rhs(i) = -result1
        ELSE
          rhs_diff(i) = 0.D0
          rhs(i) = 0
        END IF
      ENDDO
      END

